// Code generated by goctl. DO NOT EDIT.
package user

type UserRequest struct {
	Name string `uri:"name"`
	Age  int    `json:"age"`
}

type UserResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
