// Code generated by goctl. DO NOT EDIT.
package types

type UserRequest struct {
	Name   string            `uri:"name" label:"姓名"` // 姓名
	Age    int               `json:"age"`
	Embed1 []Embed1          `json:"em1" label:"xs"`  // xs
	Embed2 Embed2            `json:"em2" label:"dsd"` // dsd
	Map2   map[string]Value1 `json:"map2"`
}

type UserResponse struct {
	Code   int               `json:"code"`
	Msg    string            `json:"msg"`
	Embed1 []Embed1          `json:"em1"`
	Embed2 Embed2            `json:"em2"`
	Map1   map[string]string `json:"map1"` // test
	Map2   map[string]Value1 `json:"map2"`
}

type Embed1 struct {
	Foo    int    `json:"foo"`    // x
	Embed3 Embed3 `json:"embed3"` // esc234
}

type Embed2 struct {
	Foo int `json:"foo"` // y
}

type Embed3 struct {
	Foo int `json:"foo"` // Embed3
}

type Value1 struct {
	Name string `json:"name"` // vads3
}

type BookRequest struct {
	Name string `json:"name" label:"姓名"` // 姓名
	Age  int    `json:"age" label:"年龄"`  // 年龄
}

type BookResponse struct {
	Code int    `json:"code"` // 业务码
	Msg  string `json:"msg"`  // 业务消息
}

type CartRequest struct {
	Name string `json:"name" label:"姓名"` // 姓名
	Age  int    `json:"age" label:"年龄"`  // 年龄
}

type CartResponse struct {
	Name string `json:"name"` // 姓名
	Age  int    `json:"age"`  // 年龄
}
