// Code generated by goctl. DO NOT EDIT.
package book

import (
	"github.com/MasterJoyHunan/gengin/test/example/handler/book"
	"github.com/MasterJoyHunan/gengin/test/example/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterBookRoute(e *gin.Engine) {
	g := e.Group("/v1")
	g.Use(middleware.AuthMiddleware, middleware.SomeMiddleware, middleware.CorsMiddleware)
	g.GET("/book", book.GetBookListHandle)
	g.GET("/book/:id", book.GetBookHandle)
	g.POST("/book", book.AddBookHandle)
	g.PUT("/book/:id", book.EditBookHandle)

}
