// Code generated by goctl. DO NOT EDIT.
package cart

type CartRequest struct {
	Name string `json:"name" label:"姓名"` // 姓名
	Age  int    `json:"age" label:"年龄"`  // 年龄
}

type CartResponse struct {
	Name string `json:"name"` // 姓名
	Age  int    `json:"age"`  // 年龄
}
