// Code generated by goctl. DO NOT EDIT.
package user

import (
	"github.com/MasterJoyHunan/gengin/test/example/handler/user"
	"github.com/MasterJoyHunan/gengin/test/example/middleware"

	"github.com/gin-gonic/gin"
)

func RegisterUserRoute(e *gin.Engine) {
	g := e.Group("/v1")
	g.Use(middleware.AuthMiddleware, middleware.SomeMiddleware)
	g.GET("/user", user.GetUserListHandle)
	g.GET("/user/:id", user.GetUserHandle)
	g.POST("/user", user.AddUserHandle)
	g.PUT("/user/:id", user.EditUserHandle)

}
