// Code generated by goctl. DO NOT EDIT.
package routes

import (
	"github.com/MasterJoyHunan/gengin/test/example/handler"

	"github.com/gin-gonic/gin"
)

func RegisterRoute(e *gin.Engine) {
	g := e.Group("")
	g.GET("/ping", handler.PingHandle)
}
