// Code generated by goctl. DO NOT EDIT.
package routes

import (
	book "github.com/MasterJoyHunan/gengin/test/example/routes/book"
	swagger "github.com/MasterJoyHunan/gengin/test/example/routes/swagger"
	user "github.com/MasterJoyHunan/gengin/test/example/routes/user"
	userCart "github.com/MasterJoyHunan/gengin/test/example/routes/user/cart"

	"github.com/gin-gonic/gin"
)

func Setup(e *gin.Engine) {
	user.RegisterUserRoute(e)
	book.RegisterBookRoute(e)
	swagger.RegisterSwaggerRoute(e)
	userCart.RegisterUserCartRoute(e)
	RegisterRoute(e)
}
