// Code generated by goctl. DO NOT EDIT.
package routes

import (
	"github.com/MasterJoyHunan/gengin/test/example/routes/book"
	"github.com/MasterJoyHunan/gengin/test/example/routes/swagger"
	"github.com/MasterJoyHunan/gengin/test/example/routes/user"
	"github.com/MasterJoyHunan/gengin/test/example/routes/user/cart"

	"github.com/gin-gonic/gin"
)

func Setup(e *gin.Engine) {
	user.RegisterUserRoute(e)
	book.RegisterBookRoute(e)
	swagger.RegisterSwaggerRoute(e)
	cart.RegisterUserCartRoute(e)
	RegisterRoute(e)
}
