// Code generated by goctl. DO NOT EDIT.
package swagger

import (
	"github.com/MasterJoyHunan/gengin/test/example/handler/swagger"

	"github.com/gin-gonic/gin"
)

func RegisterSwaggerRoute(e *gin.Engine) {
	g := e.Group("")
	g.GET("/swagger", swagger.SwaggerHandle)

}
