// Code generated by goctl. DO NOT EDIT.
package routes

import (
    {{- range .routes}}
    {{if not (eq .pkg "routes")}}{{.alias}} "{{$.rootPkg}}/{{.pkg}}"{{end}}
    {{- end}}

	"github.com/gin-gonic/gin"
)

func Setup(e *gin.Engine) {
    {{- range .routes}}
    {{if not (eq .base "routes")}}{{.alias}}.{{end}}Register{{.name}}Route(e)
    {{- end}}
}
